import matplotlib.pyplot as plt
import numpy as np
np.random.seed(0)
weights1 = np.random.uniform(55, 65, 10)
heights1 = np.random.uniform(120, 180, 10)
weights2 = np.random.uniform(60, 70, 10)
heights2 = np.random.uniform(140, 200, 10)
weights3 = np.random.uniform(65, 75, 10)
heights3 = np.random.uniform(160, 220, 10)
plt.figure(figsize=(10, 6))
plt.scatter(weights1, heights1, color='blue', marker='*', label='Group 1')
plt.scatter(weights2, heights2, color='red', marker='*', label='Group 2')
plt.scatter(weights3, heights3, color='green', marker='*', label='Group 3')
plt.xlabel('Weight')
plt.ylabel('Height')
plt.title('Group wise Weight vs Height scatter plot')
plt.xlim(55, 75)
plt.ylim(100, 240)
plt.legend()
plt.grid(True)
plt.show()
